version: '3.8'

name: otto

services:
  
  city-api:
    image: city-api
    build:
      context: .
      dockerfile: ../src/api/Otto.CityApi/Dockerfile
    restart: always
    depends_on: 
      - city-db
    ports:
      - "5000:80"
    command: ["dotnet", "ef", "database update", "-s ../src/api/CityApi", "-p ../src/storage/Otto.Storage.City"]
  
  city-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=,frfkjdf
    ports:
      - "5001:5432"
  
  proxy:
    image: nginx:1.25.2
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - city-api
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf