version: '3.8'

name: otto

services:
  
  client-app:
    hostname: client-app
    build: 
      context: ../src/client-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6000:443"
      - "6001:80"
  
  proxy:
    build:     
      context: proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - CLIENTAPP_PORT=6000
    depends_on: 
      - client-app